### ISSUE TITLE
This doesn't run against the current release of Neo4J

### ISSUE THREAD

**Issue by mcclown** [neo4j-examples/movies-dotnet-bolt#8]
I get an error saying:

NotSupportedException: The Neo4j Server doesn't support this client.

Tried against Neo4j 4.0.3

**Comment by jkhaui** [comment]
Same.

**Comment by hspies91** [comment]
Same..

**Comment by fbiville** [comment]
You might want to try https://github.com/neo4j-examples/movies-dotnetcore-bolt in the meantime.

**Comment by fbiville** [comment]
After chatting with my .NET colleagues, we're going to archive this repo and only keep the aforementioned one.
